# Generated by Django 3.2 on 2021-04-14 07:56


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import json.decoder


class Migration(migrations.Migration):
    dependencies = ('DjAIData', '0001_DataSet'),

    operations = [
        migrations.CreateModel(
            name='JSONDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='json_data_sets',
                    serialize=False, to='DjAIData.dataset')),

                ('json',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='JSON Data Content',
                    null=True,
                    verbose_name='JSON Data Content'))
            ],

            options={
                'verbose_name': 'JSON Data Set',
                'verbose_name_plural': 'JSON Data Sets',
                'db_table': 'DjAIData_JSONDataSet',
                'abstract': False,
                'default_related_name': 'json_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.dataset',)
        ),

        migrations.CreateModel(
            name='NamedJSONDataSet',

            fields=[
                ('jsondataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='named_json_data_sets',
                    serialize=False,
                    to='DjAIData.jsondataset')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name'))
            ],

            options={
                'verbose_name': 'Named JSON Data Set',
                'verbose_name_plural': 'Named JSON Data Sets',
                'db_table': 'DjAIData_NamedJSONDataSet',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': 'named_json_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.jsondataset',
                   models.Model)
        )
    ]
