# Generated by Django 3.2 on 2021-04-14 08:02


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import json.decoder


class Migration(migrations.Migration):
    dependencies = ('DjAIData', '0002_JSONDataSet'),

    operations = [
        migrations.CreateModel(
            name='NumPyArray',

            fields=[
                ('jsondataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='numpy_arrays',
                    serialize=False,
                    to='DjAIData.jsondataset')),

                ('dtype',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Data Type(s)',
                    verbose_name='Data Type(s)'))
            ],

            options={
                'verbose_name': 'NumPy Array',
                'verbose_name_plural': 'NumPy Arrays',
                'db_table': 'DjAIData_NumPyArray',
                'abstract': False,
                'default_related_name': 'numpy_arrays',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.jsondataset',)
        ),

        migrations.CreateModel(
            name='NamedNumPyArray',

            fields=[
                ('numpyarray_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='named_numpy_arrays',
                    serialize=False,
                    to='DjAIData.numpyarray')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name'))
            ],

            options={
                'verbose_name': 'Named NumPy Array',
                'verbose_name_plural': 'Named NumPy Arrays',
                'db_table': 'DjAIData_NamedNumPyArray',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': 'named_numpy_arrays',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.numpyarray',
                   models.Model)
        )
    ]
