# Generated by Django 3.2 on 2021-04-14 08:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('DjAIData', '0003_NumPyArray'),

    operations = [
        migrations.CreateModel(
            name='PandasDataFrame',

            fields=[
                ('jsondataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='pandas_dataframes',
                    serialize=False,
                    to='DjAIData.jsondataset'))
            ],

            options={
                'verbose_name': 'Pandas DataFrame',
                'verbose_name_plural': 'Pandas DataFrames',
                'db_table': 'DjAIData_PandasDataFrame',
                'abstract': False,
                'default_related_name': 'pandas_dataframes',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.jsondataset',)
        ),

        migrations.CreateModel(
            name='NamedPandasDataFrame',

            fields=[
                ('pandasdataframe_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='named_pandas_dataframes',
                    serialize=False,
                    to='DjAIData.pandasdataframe')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name'))
            ],

            options={
                'verbose_name': 'Named Pandas DataFrame',
                'verbose_name_plural': 'Named Pandas DataFrames',
                'db_table': 'DjAIData_NamedPandasDataFrame',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': 'named_pandas_dataframes',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.pandasdataframe',
                   models.Model)
        )
    ]
