# Generated by Django 3.2 on 2021-04-14 08:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('DjAIData', '0004_PandasDataFrame'),

    operations = [
        migrations.CreateModel(
            name='ParquetDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='parquet_data_sets',
                    serialize=False,
                    to='DjAIData.dataset')),

                ('path',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Path/URL',
                    max_length=255,
                    verbose_name='Data Set Path/URL')),

                ('is_dir',
                 models.BooleanField(
                    db_index=True,
                    default=False,
                    help_text='Data Set Path/URL is Directory?',
                    verbose_name='Data Set Path/URL is Directory?'))
            ],

            options={
                'verbose_name': 'Parquet Data Set',
                'verbose_name_plural': 'Parquet Data Sets',
                'db_table': 'DjAIData_ParquetDataSet',
                'abstract': False,
                'default_related_name': 'parquet_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.dataset',)
        ),

        migrations.CreateModel(
            name='NamedParquetDataSet',

            fields=[
                ('parquetdataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='named_parquet_data_sets',
                    serialize=False,
                    to='DjAIData.parquetdataset')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name'))
            ],

            options={
                'verbose_name': 'Named Parquet Data Set',
                'verbose_name_plural': 'Named Parquet Data Sets',
                'db_table': 'DjAIData_NamedParquetDataSet',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': 'named_parquet_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.parquetdataset',
                   models.Model)
        )
    ]
