"""
Django settings for DjAI project

Generated by 'django-admin startproject' using Django

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings
"""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '???'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    # Django Admin Themes: add to INSTALLED_APPS before django.contrib.admin
    'jazzmin',

    # Django Default/Main Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django Extensions: Extra Management Commands
    'django_extensions',

    # Django REST Framework UI Templates
    'rest_framework',

    # CORS Headers
    'corsheaders',

    # Query Profiling
    'silk',

    # DjAI Modules
    'djai.data',
    'djai.model'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'silk.middleware.SilkyMiddleware'
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    dict(
        BACKEND='django.template.backends.django.DjangoTemplates',
        DIRS=[],
        APP_DIRS=True,
        OPTIONS=dict(
                    context_processors=[
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                    ]
                )
    )
]


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases
DATABASES = {
    'default': dict(
        ENGINE='django.db.backends.sqlite3',
        NAME='db.sqlite3'
    )
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    dict(NAME='django.contrib.auth.password_validation.'
              'UserAttributeSimilarityValidator'),
    dict(NAME='django.contrib.auth.password_validation.'
              'MinimumLengthValidator'),
    dict(NAME='django.contrib.auth.password_validation.'
              'CommonPasswordValidator'),
    dict(NAME='django.contrib.auth.password_validation.'
              'NumericPasswordValidator')
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files
STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.fields.AutoField'
