# Generated by Django 3.2 on 2021-04-14 08:29


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('DjAIData', '0006_CSVDataSet'),

    operations = [
        migrations.CreateModel(
            name='TFRecordDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='tfrecord_data_sets',
                    serialize=False,
                    to='DjAIData.dataset')),

                ('path',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Path/URL',
                    max_length=255,
                    verbose_name='Data Set Path/URL')),

                ('is_dir',
                 models.BooleanField(
                    db_index=True,
                    default=False,
                    help_text='Data Set Path/URL is Directory?',
                    verbose_name='Data Set Path/URL is Directory?'))
            ],

            options={
                'verbose_name': 'TFRecord Data Set',
                'verbose_name_plural': 'TFRecord Data Sets',
                'db_table': 'DjAIData_TFRecordDataSet',
                'abstract': False,
                'default_related_name': 'tfrecord_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.dataset',)
        ),

        migrations.CreateModel(
            name='NamedTFRecordDataSet',

            fields=[
                ('tfrecorddataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='named_tfrecord_data_sets',
                    serialize=False,
                    to='DjAIData.tfrecorddataset')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name'))
            ],

            options={
                'verbose_name': 'Named TFRecord Data Set',
                'verbose_name_plural': 'Named TFRecord Data Sets',
                'db_table': 'DjAIData_NamedTFRecordDataSet',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': 'named_tfrecord_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('DjAIData.tfrecorddataset',
                   models.Model)
        )
    ]
