# Generated by Django 3.2 on 2021-04-14 09:16


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('DjAIModel', '0002_SKLModel'),

    operations = [
        migrations.CreateModel(
            name='KerasModel',

            fields=[
                ('aimodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='keras_models',
                    serialize=False,
                    to='DjAIModel.aimodel')),

                ('artifact',
                 models.BinaryField(
                    default=None,
                    help_text='Model Artifact (raw binary data)',
                    verbose_name='Model Artifact (raw binary data)'))
            ],

            options={
                'verbose_name': 'Keras Model',
                'verbose_name_plural': 'Keras Models',
                'db_table': 'DjAIModel_KerasModel',
                'abstract': False,
                'default_related_name': 'keras_models',
                'base_manager_name': 'objects'
            },

            bases=('DjAIModel.aimodel',)
        ),

        migrations.CreateModel(
            name='TFModel',

            fields=[
                ('aimodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='tf_models',
                    serialize=False,
                    to='DjAIModel.aimodel')),

                ('artifact',
                 models.BinaryField(
                    default=None,
                    help_text='Model Artifact (raw binary data)',
                    verbose_name='Model Artifact (raw binary data)'))
            ],

            options={
                'verbose_name': 'TensorFlow Model',
                'verbose_name_plural': 'TensorFlow Models',
                'db_table': 'DjAIModel_TFModel',
                'abstract': False,
                'default_related_name': 'tf_models',
                'base_manager_name': 'objects'
            },

            bases=('DjAIModel.aimodel',)
        ),

        migrations.CreateModel(
            name='TorchModel',

            fields=[
                ('aimodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='torch_models',
                    serialize=False,
                    to='DjAIModel.aimodel')),

                ('artifact',
                 models.BinaryField(
                    default=None,
                    help_text='Model Artifact (raw binary data)',
                    verbose_name='Model Artifact (raw binary data)'))
            ],

            options={
                'verbose_name': 'Torch Model',
                'verbose_name_plural': 'Torch Models',
                'db_table': 'DjAIModel_TorchModel',
                'abstract': False,
                'default_related_name': 'torch_models',
                'base_manager_name': 'objects'
            },

            bases=('DjAIModel.aimodel',)
        )
    ]
